# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(740, 600)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        HomePage.setFont(font)
        self.centralwidget = QtWidgets.QWidget(HomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBody = QtWidgets.QFrame(self.frame_2)
        self.menuBody.setMaximumSize(QtCore.QSize(500, 16777215))
        self.menuBody.setStyleSheet("background-color: rgb(255, 246, 251);")
        self.menuBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBody.setObjectName("menuBody")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menuBody)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.body = QtWidgets.QStackedWidget(self.menuBody)
        self.body.setStyleSheet("QPushButtonr{\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.body.setObjectName("body")
        self.Hpage = QtWidgets.QWidget()
        self.Hpage.setObjectName("Hpage")
        self.label_2 = QtWidgets.QLabel(self.Hpage)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 341, 221))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Hpage)
        self.label_3.setGeometry(QtCore.QRect(130, 360, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.body.addWidget(self.Hpage)
        self.Kpage = QtWidgets.QWidget()
        self.Kpage.setObjectName("Kpage")
        self.label_8 = QtWidgets.QLabel(self.Kpage)
        self.label_8.setGeometry(QtCore.QRect(360, 100, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.Kpage)
        self.label_11.setGeometry(QtCore.QRect(10, 130, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Kpage)
        self.label_12.setGeometry(QtCore.QRect(80, 150, 371, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.openKlogFile = QtWidgets.QPushButton(self.Kpage)
        self.openKlogFile.setGeometry(QtCore.QRect(200, 490, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.openKlogFile.setFont(font)
        self.openKlogFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openKlogFile.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.openKlogFile.setObjectName("openKlogFile")
        self.label_13 = QtWidgets.QLabel(self.Kpage)
        self.label_13.setGeometry(QtCore.QRect(340, 500, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.enableKservice = QtWidgets.QCheckBox(self.Kpage)
        self.enableKservice.setGeometry(QtCore.QRect(340, 280, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.enableKservice.setFont(font)
        self.enableKservice.setObjectName("enableKservice")
        self.label_14 = QtWidgets.QLabel(self.Kpage)
        self.label_14.setGeometry(QtCore.QRect(100, 170, 351, 20))
        self.label_14.setObjectName("label_14")
        self.submitK = QtWidgets.QPushButton(self.Kpage)
        self.submitK.setGeometry(QtCore.QRect(200, 330, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.submitK.setFont(font)
        self.submitK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitK.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.submitK.setObjectName("submitK")
        self.label_15 = QtWidgets.QLabel(self.Kpage)
        self.label_15.setGeometry(QtCore.QRect(100, 240, 351, 20))
        self.label_15.setObjectName("label_15")
        self.label_6 = QtWidgets.QLabel(self.Kpage)
        self.label_6.setGeometry(QtCore.QRect(20, 0, 431, 31))
        self.label_6.setObjectName("label_6")
        self.label_31 = QtWidgets.QLabel(self.Kpage)
        self.label_31.setGeometry(QtCore.QRect(-10, 200, 491, 20))
        self.label_31.setObjectName("label_31")
        self.label_35 = QtWidgets.QLabel(self.Kpage)
        self.label_35.setGeometry(QtCore.QRect(-10, 400, 491, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.Kpage)
        self.label_36.setGeometry(QtCore.QRect(100, 450, 351, 20))
        self.label_36.setObjectName("label_36")
        self.body.addWidget(self.Kpage)
        self.Spage = QtWidgets.QWidget()
        self.Spage.setObjectName("Spage")
        self.label_16 = QtWidgets.QLabel(self.Spage)
        self.label_16.setGeometry(QtCore.QRect(350, 100, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Spage)
        self.label_17.setGeometry(QtCore.QRect(10, 240, 441, 20))
        self.label_17.setObjectName("label_17")
        self.submitS = QtWidgets.QPushButton(self.Spage)
        self.submitS.setGeometry(QtCore.QRect(20, 330, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.submitS.setFont(font)
        self.submitS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitS.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.submitS.setObjectName("submitS")
        self.enableSservice = QtWidgets.QCheckBox(self.Spage)
        self.enableSservice.setGeometry(QtCore.QRect(330, 280, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.enableSservice.setFont(font)
        self.enableSservice.setObjectName("enableSservice")
        self.openSlogFile = QtWidgets.QPushButton(self.Spage)
        self.openSlogFile.setGeometry(QtCore.QRect(210, 490, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.openSlogFile.setFont(font)
        self.openSlogFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openSlogFile.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.openSlogFile.setObjectName("openSlogFile")
        self.label_32 = QtWidgets.QLabel(self.Spage)
        self.label_32.setGeometry(QtCore.QRect(340, 500, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_19 = QtWidgets.QLabel(self.Spage)
        self.label_19.setGeometry(QtCore.QRect(10, 0, 451, 31))
        self.label_19.setObjectName("label_19")
        self.label_37 = QtWidgets.QLabel(self.Spage)
        self.label_37.setGeometry(QtCore.QRect(0, 210, 491, 20))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.Spage)
        self.label_38.setGeometry(QtCore.QRect(-10, 400, 491, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Spage)
        self.label_39.setGeometry(QtCore.QRect(110, 450, 351, 20))
        self.label_39.setObjectName("label_39")
        self.label_44 = QtWidgets.QLabel(self.Spage)
        self.label_44.setGeometry(QtCore.QRect(0, 130, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_47 = QtWidgets.QLabel(self.Spage)
        self.label_47.setGeometry(QtCore.QRect(126, 330, 331, 51))
        self.label_47.setObjectName("label_47")
        self.time = QtWidgets.QLineEdit(self.Spage)
        self.time.setGeometry(QtCore.QRect(170, 330, 41, 21))
        self.time.setObjectName("time")
        self.body.addWidget(self.Spage)
        self.Apage = QtWidgets.QWidget()
        self.Apage.setObjectName("Apage")
        self.label_33 = QtWidgets.QLabel(self.Apage)
        self.label_33.setGeometry(QtCore.QRect(360, 90, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.openAfile = QtWidgets.QPushButton(self.Apage)
        self.openAfile.setGeometry(QtCore.QRect(170, 290, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.openAfile.setFont(font)
        self.openAfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openAfile.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.openAfile.setObjectName("openAfile")
        self.label_34 = QtWidgets.QLabel(self.Apage)
        self.label_34.setGeometry(QtCore.QRect(270, 290, 181, 20))
        self.label_34.setObjectName("label_34")
        self.label_7 = QtWidgets.QLabel(self.Apage)
        self.label_7.setGeometry(QtCore.QRect(230, 340, 251, 20))
        self.label_7.setObjectName("label_7")
        self.Download = QtWidgets.QPushButton(self.Apage)
        self.Download.setGeometry(QtCore.QRect(130, 340, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Download.setFont(font)
        self.Download.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Download.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.Download.setObjectName("Download")
        self.label_20 = QtWidgets.QLabel(self.Apage)
        self.label_20.setGeometry(QtCore.QRect(0, 0, 471, 31))
        self.label_20.setObjectName("label_20")
        self.label_40 = QtWidgets.QLabel(self.Apage)
        self.label_40.setGeometry(QtCore.QRect(-10, 250, 491, 20))
        self.label_40.setObjectName("label_40")
        self.label_43 = QtWidgets.QLabel(self.Apage)
        self.label_43.setGeometry(QtCore.QRect(0, 120, 451, 111))
        self.label_43.setObjectName("label_43")
        self.body.addWidget(self.Apage)
        self.Fpage = QtWidgets.QWidget()
        self.Fpage.setObjectName("Fpage")
        self.label_21 = QtWidgets.QLabel(self.Fpage)
        self.label_21.setGeometry(QtCore.QRect(-4, -10, 481, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.Fpage)
        self.label_22.setGeometry(QtCore.QRect(400, 60, 47, 13))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.Fpage)
        self.label_23.setGeometry(QtCore.QRect(50, 190, 401, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Fpage)
        self.label_24.setGeometry(QtCore.QRect(-20, 320, 471, 41))
        self.label_24.setObjectName("label_24")
        self.submitF = QtWidgets.QPushButton(self.Fpage)
        self.submitF.setGeometry(QtCore.QRect(200, 530, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.submitF.setFont(font)
        self.submitF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitF.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.submitF.setObjectName("submitF")
        self.enableFservice = QtWidgets.QCheckBox(self.Fpage)
        self.enableFservice.setGeometry(QtCore.QRect(310, 460, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.enableFservice.setFont(font)
        self.enableFservice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enableFservice.setObjectName("enableFservice")
        self.label_25 = QtWidgets.QLabel(self.Fpage)
        self.label_25.setGeometry(QtCore.QRect(100, 430, 391, 20))
        self.label_25.setObjectName("label_25")
        self.BlackLitField = QtWidgets.QLineEdit(self.Fpage)
        self.BlackLitField.setGeometry(QtCore.QRect(180, 230, 271, 31))
        self.BlackLitField.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"font: 11pt \"Nirmala UI\";\n"
"gridline-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.BlackLitField.setText("")
        self.BlackLitField.setObjectName("BlackLitField")
        self.submitF_2 = QtWidgets.QPushButton(self.Fpage)
        self.submitF_2.setGeometry(QtCore.QRect(70, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.submitF_2.setFont(font)
        self.submitF_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitF_2.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.submitF_2.setObjectName("submitF_2")
        self.label_26 = QtWidgets.QLabel(self.Fpage)
        self.label_26.setGeometry(QtCore.QRect(-10, 160, 491, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.Fpage)
        self.label_27.setGeometry(QtCore.QRect(0, 300, 491, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.Fpage)
        self.label_28.setGeometry(QtCore.QRect(0, 410, 491, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.Fpage)
        self.label_29.setGeometry(QtCore.QRect(370, 380, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.Fpage)
        self.label_30.setGeometry(QtCore.QRect(210, 380, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_45 = QtWidgets.QLabel(self.Fpage)
        self.label_45.setGeometry(QtCore.QRect(360, 50, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.Fpage)
        self.label_46.setGeometry(QtCore.QRect(20, 80, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.StartTime = QtWidgets.QLineEdit(self.Fpage)
        self.StartTime.setGeometry(QtCore.QRect(320, 380, 41, 20))
        self.StartTime.setObjectName("StartTime")
        self.EndTime = QtWidgets.QLineEdit(self.Fpage)
        self.EndTime.setGeometry(QtCore.QRect(170, 380, 41, 20))
        self.EndTime.setObjectName("EndTime")
        self.msg = QtWidgets.QLabel(self.Fpage)
        self.msg.setGeometry(QtCore.QRect(20, 269, 431, 31))
        self.msg.setText("")
        self.msg.setObjectName("msg")
        self.checkAdmin = QtWidgets.QLabel(self.Fpage)
        self.checkAdmin.setGeometry(QtCore.QRect(30, 490, 431, 31))
        self.checkAdmin.setText("")
        self.checkAdmin.setObjectName("checkAdmin")
        self.body.addWidget(self.Fpage)
        self.Cpage = QtWidgets.QWidget()
        self.Cpage.setObjectName("Cpage")
        self.userNameField = QtWidgets.QLineEdit(self.Cpage)
        self.userNameField.setGeometry(QtCore.QRect(70, 160, 271, 31))
        self.userNameField.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"font: 11pt \"Nirmala UI\";\n"
"gridline-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.userNameField.setText("")
        self.userNameField.setObjectName("userNameField")
        self.emailField = QtWidgets.QLineEdit(self.Cpage)
        self.emailField.setGeometry(QtCore.QRect(70, 220, 271, 41))
        self.emailField.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"font: 11pt \"Nirmala UI\";\n"
"gridline-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.emailField.setText("")
        self.emailField.setObjectName("emailField")
        self.commantField = QtWidgets.QLineEdit(self.Cpage)
        self.commantField.setGeometry(QtCore.QRect(70, 280, 271, 221))
        self.commantField.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"font: 11pt \"Nirmala UI\";\n"
"gridline-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.commantField.setText("")
        self.commantField.setObjectName("commantField")
        self.send = QtWidgets.QPushButton(self.Cpage)
        self.send.setGeometry(QtCore.QRect(150, 530, 111, 50))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.send.setFont(font)
        self.send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send.setStyleSheet("QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 207, 233);\n"
"border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}")
        self.send.setObjectName("send")
        self.label_9 = QtWidgets.QLabel(self.Cpage)
        self.label_9.setGeometry(QtCore.QRect(350, 170, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Cpage)
        self.label_10.setGeometry(QtCore.QRect(350, 230, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.Cpage)
        self.label_4.setGeometry(QtCore.QRect(-4, 50, 481, 81))
        self.label_4.setObjectName("label_4")
        self.label_18 = QtWidgets.QLabel(self.Cpage)
        self.label_18.setGeometry(QtCore.QRect(350, 340, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_5 = QtWidgets.QLabel(self.Cpage)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 471, 20))
        self.label_5.setObjectName("label_5")
        self.body.addWidget(self.Cpage)
        self.verticalLayout_3.addWidget(self.body)
        self.horizontalLayout_2.addWidget(self.menuBody)
        self.menuServices = QtWidgets.QFrame(self.frame_2)
        self.menuServices.setMinimumSize(QtCore.QSize(0, 0))
        self.menuServices.setMaximumSize(QtCore.QSize(250, 16777215))
        self.menuServices.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuServices.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuServices.setObjectName("menuServices")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menuServices)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.menuServices)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setStyleSheet("background-color: rgb(255, 221, 246);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_41 = QtWidgets.QLabel(self.frame_5)
        self.label_41.setGeometry(QtCore.QRect(30, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.menuIcon = QtWidgets.QLabel(self.frame_5)
        self.menuIcon.setGeometry(QtCore.QRect(170, 0, 61, 51))
        self.menuIcon.setObjectName("menuIcon")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.menuServices)
        self.frame_6.setStyleSheet("background-color: rgb(255, 221, 246);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.filterWeb = QtWidgets.QPushButton(self.frame_6)
        self.filterWeb.setGeometry(QtCore.QRect(20, 220, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.filterWeb.setFont(font)
        self.filterWeb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.filterWeb.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"    font: 75 12pt \"Arial Narrow\";\n"
"}")
        self.filterWeb.setObjectName("filterWeb")
        self.contactUs = QtWidgets.QPushButton(self.frame_6)
        self.contactUs.setGeometry(QtCore.QRect(20, 330, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.contactUs.setFont(font)
        self.contactUs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactUs.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"    font: 75 12pt \"Arial Narrow\";\n"
"}")
        self.contactUs.setObjectName("contactUs")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(0, 280, 221, 20))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.adBlock = QtWidgets.QPushButton(self.frame_6)
        self.adBlock.setGeometry(QtCore.QRect(20, 160, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.adBlock.setFont(font)
        self.adBlock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adBlock.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"    font: 75 12pt \"Arial Narrow\";\n"
"}")
        self.adBlock.setObjectName("adBlock")
        self.secreenshot = QtWidgets.QPushButton(self.frame_6)
        self.secreenshot.setGeometry(QtCore.QRect(20, 100, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.secreenshot.setFont(font)
        self.secreenshot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.secreenshot.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"    font: 75 12pt \"Arial Narrow\";\n"
"}")
        self.secreenshot.setObjectName("secreenshot")
        self.keylogging = QtWidgets.QPushButton(self.frame_6)
        self.keylogging.setGeometry(QtCore.QRect(20, 40, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.keylogging.setFont(font)
        self.keylogging.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.keylogging.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:white;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"    font: 75 12pt \"Arial Narrow\";\n"
"}")
        self.keylogging.setObjectName("keylogging")
        self.label_42 = QtWidgets.QLabel(self.frame_6)
        self.label_42.setGeometry(QtCore.QRect(0, 380, 221, 20))
        self.label_42.setStyleSheet("")
        self.label_42.setObjectName("label_42")
        self.logoutIcon = QtWidgets.QLabel(self.frame_6)
        self.logoutIcon.setGeometry(QtCore.QRect(70, 460, 51, 41))
        self.logoutIcon.setObjectName("logoutIcon")
        self.LogOut = QtWidgets.QPushButton(self.frame_6)
        self.LogOut.setGeometry(QtCore.QRect(100, 462, 75, 31))
        self.LogOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogOut.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"\n"
"\n"
"    font: 75 9pt \"Arial Narrow\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"font: 75 10pt \"Arial Narrow\";\n"
"\n"
"}")
        self.LogOut.setObjectName("LogOut")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.menuServices)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        HomePage.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomePage)
        self.body.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "ICU_Services"))
        self.label_2.setText(_translate("HomePage", "<html><head/><body><p><img src=\":/logo/ICU_logo_.png\"/></p></body></html>"))
        self.label_3.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#aa557f;\">Keep Them </span><span style=\" font-size:18pt; text-decoration: underline; color:#aa557f;\">PROTECT </span></p><p align=\"center\"><span style=\" font-size:18pt; color:#aa557f;\">Keep Them </span><span style=\" font-size:18pt; text-decoration: underline; color:#aa557f;\">Safe</span></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.label_8.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">:service description</span></p></body></html>"))
        self.label_11.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#aa557f;\">،This service records every press of the enter key on the child's device (keyboard).</span></p></body></html>"))
        self.label_12.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:10pt; color:#aa557f;\">.It captures and records the enter keystrokes and saves them to a log file</span></p></body></html>"))
        self.openKlogFile.setText(_translate("HomePage", "open file "))
        self.label_13.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:10pt;\">:view logs</span></p></body></html>"))
        self.enableKservice.setText(_translate("HomePage", "enable service "))
        self.label_14.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:10pt; color:#aa557f;\">.when enable </span><span style=\" font-size:10pt; text-decoration: underline; color:#aa557f;\">notification</span><span style=\" font-size:10pt; color:#aa557f;\"> An alert will be sent in real time</span></p></body></html>"))
        self.submitK.setText(_translate("HomePage", "enable "))
        self.label_15.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#ff557f;\">&quot;Please select the option below, then click &quot;</span><span style=\" font-size:10pt; font-weight:600; text-decoration: underline; color:#ff557f;\">enable</span><span style=\" font-size:10pt; font-weight:600; color:#ff557f;\">*</span></p></body></html>"))
        self.label_6.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#aa557f;\">** Keylogging Service**</span></p></body></html>"))
        self.label_31.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_35.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_36.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#ff557f;\">click on</span><span style=\" font-size:10pt; font-weight:600; color:#ff557f;\"> &quot; open file&quot; </span><span style=\" font-size:10pt; color:#ff557f;\">to view logs file*</span><span style=\" font-size:10pt; font-weight:600; color:#ff557f;\"/></p></body></html>"))
        self.label_16.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">:service description</span></p></body></html>"))
        self.label_17.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff557f;\">&quot;Please select the following option and select a time for screenshots, then click &quot;</span><span style=\" font-size:10pt; font-weight:600; text-decoration: underline; color:#ff557f;\">enable service</span><span style=\" font-size:10pt; font-weight:600; color:#ff557f;\">*</span></p></body></html>"))
        self.submitS.setText(_translate("HomePage", "enable service "))
        self.enableSservice.setText(_translate("HomePage", "enable service "))
        self.openSlogFile.setText(_translate("HomePage", "open file "))
        self.label_32.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:10pt;\">:view logsل</span></p></body></html>"))
        self.label_19.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#aa557f;\">** Screenshot Service**</span></p></body></html>"))
        self.label_37.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_38.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_39.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#ff557f;\">click on</span><span style=\" font-size:10pt; font-weight:600; color:#ff557f;\"> &quot; open file&quot; </span><span style=\" font-size:10pt; color:#ff557f;\">to view logs file*</span><span style=\" font-size:10pt; font-weight:600; color:#ff557f;\"/></p></body></html>"))
        self.label_44.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:9pt; color:#aa557f;\">.This service allows taking screenshots that capture the contents of the child's screen every certain period of time</span></p><p align=\"right\"><span style=\" font-size:9pt; color:#aa557f;\">.Also enables real-time alerting and viewing of saved screenshots history</span></p></body></html>"))
        self.label_47.setText(_translate("HomePage", "<html><head/><body><p align=\"right\">أ<span style=\" color:#ff007f;\">Enter the appropriate time to take a screenshot (in minutes) </span></p><p align=\"right\"><span style=\" text-decoration: underline; color:#ff007f;\">Where if you want to activate the screenshot for every hour, please enter the number (60) ***</span></p></body></html>"))
        self.label_33.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#000000;\">:service description</span></p></body></html>"))
        self.openAfile.setText(_translate("HomePage", "open "))
        self.label_34.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#ff557f;\">click on </span><span style=\" font-size:10pt; font-weight:600; text-decoration: underline; color:#ff557f;\">open</span><span style=\" font-size:10pt; color:#ff557f;\"> To open the extension folder*</span></p></body></html>"))
        self.label_7.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff557f;\">click on </span><span style=\" font-size:10pt; font-weight:600; color:#ff557f;\">download</span><span style=\" font-size:10pt; color:#ff557f;\"> To view installation instructions* </span></p></body></html>"))
        self.Download.setText(_translate("HomePage", "download"))
        self.label_20.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#aa557f;\">** Ad Block Service**</span></p></body></html>"))
        self.label_40.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_43.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:9pt; color:#aa557f;\">This service enables the browser (Chrome) to block all advertisements that appear on websites</span></p><p align=\"right\"><br/></p><p align=\"right\"><span style=\" font-size:9pt; color:#aa557f;\">To activate this service, you must download the help file to install the extension folder on your browser (Chrome). *</span></p></body></html>"))
        self.label_21.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#aa557f;\">** Filter Website Service**</span></p></body></html>"))
        self.label_23.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:9pt; color:#ff557f;\"> Enter the site you want the restrictions to apply (add it to the blacklist)* </span></p></body></html>"))
        self.label_24.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:9pt; color:#ff557f;\">Please specify the period of restrictions by specifying the start time and end time* </span></p><p align=\"right\"><span style=\" font-size:9pt; color:#ff557f;\">&quot;Note that the regular system is a 24-hour system, so enter a number only &quot; </span></p></body></html>"))
        self.submitF.setText(_translate("HomePage", "enable "))
        self.enableFservice.setText(_translate("HomePage", " enable this service "))
        self.label_25.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:9pt; color:#ff557f;\">&quot;Please, if you want to activate the service, select the option below and then click on &quot;</span><span style=\" font-size:9pt; font-weight:600; text-decoration: underline; color:#ff557f;\">enable</span><span style=\" font-size:9pt; font-weight:600; color:#ff557f;\">*</span></p></body></html>"))
        self.submitF_2.setText(_translate("HomePage", "add "))
        self.label_26.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_27.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_28.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</span></p></body></html>"))
        self.label_29.setText(_translate("HomePage", "start time:"))
        self.label_30.setText(_translate("HomePage", "end time:"))
        self.label_45.setText(_translate("HomePage", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#000000;\">:service descripton</span></p></body></html>"))
        self.label_46.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:9pt; color:#aa557f;\">This service allows the creation of a blacklist of sites to be filtered or blocked </span></p><p align=\"right\"><span style=\" font-size:9pt; color:#aa557f;\">.It also allows setting a time for restrictions so that it is forbidden to open certain applications or sites during the specified period</span></p></body></html>"))
        self.send.setText(_translate("HomePage", "send"))
        self.label_9.setText(_translate("HomePage", "username: "))
        self.label_10.setText(_translate("HomePage", "email: "))
        self.label_4.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ff557f;\">Do you have questions or comments?</span></p><p align=\"center\"><span style=\" font-size:9pt; color:#ff557f;\">Feel free to send a message to the technical support team via the form below and we will be happy to assist you</span></p></body></html>"))
        self.label_18.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:9pt;\">questions</span></p><p align=\"right\"><span style=\" font-size:9pt;\">or comments? </span></p></body></html>"))
        self.label_5.setText(_translate("HomePage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#aa557f;\">** Contact Us **</span></p></body></html>"))
        self.label_41.setText(_translate("HomePage", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:400; color:#cea4c3;\">Service List</span></p></body></html>"))
        self.menuIcon.setText(_translate("HomePage", "<html><head/><body><p><img src=\":/icons/menu_.png\"/></p></body></html>"))
        self.filterWeb.setText(_translate("HomePage", "Filter Website"))
        self.contactUs.setText(_translate("HomePage", "Contact Us"))
        self.label.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">______________________________________</span></p></body></html>"))
        self.adBlock.setText(_translate("HomePage", "Ad Block"))
        self.secreenshot.setText(_translate("HomePage", "Screenshot"))
        self.keylogging.setText(_translate("HomePage", "Keylogging"))
        self.label_42.setText(_translate("HomePage", "<html><head/><body><p><span style=\" color:#ffcfe9;\">______________________________________</span></p></body></html>"))
        self.logoutIcon.setText(_translate("HomePage", "<html><head/><body><p><img src=\":/icons/logoutICON_.png\"/></p></body></html>"))
        self.LogOut.setText(_translate("HomePage", "logout"))
import icons
import logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomePage = QtWidgets.QMainWindow()
    ui = Ui_HomePage()
    ui.setupUi(HomePage)
    HomePage.show()
    sys.exit(app.exec_())
